spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthorizationHeaderFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

