spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/users-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
