eureka:
  client:
    register-with-eureka: false  # Eureka Server, kendini kayıt etmeye çalışmaz
    fetch-registry: false        # Diğer servislerden kayıt bilgisi almaya çalışmaz
  server:
    enable-self-preservation: false